# Example scene configuration for rheidos/examples/point_selection.py

meshes:
  - path: ../../../models/bunny.obj
    name: bunny
    center: true
    transform:
      position: [0.0, 0.0, 0.2]
      hpr: [0.0, 90.0, 0.0]
      scale: 1.0
    material:
      diffuse: [0.80, 0.82, 0.90, 1.0]
      specular: [1.0, 1.0, 1.0, 1.0]
      shininess: 64
    wireframe: false
    two_sided: false
    pickable: true

camera:
  auto_frame: true
  offset_dir: [1.4, -2.6, 1.2]
  distance_scale: 3.0

lights:
  ambient: [0.18, 0.18, 0.22, 1.0]
  directionals:
    - name: key
      color: [0.85, 0.85, 0.90, 1.0]
      hpr: [-35, -45, 0]
    - name: fill
      color: [0.35, 0.35, 0.45, 1.0]
      hpr: [60, -20, 0]

studio:
  enabled: true
  ground_size: 20
  ground_tiles: 40
  snap_ground_to_bounds: true
  ground_margin: 0.02

# Optional plug-and-play components built via factories (see rheidos/examples/scene_factories.py)
views:
  - factory: rheidos.examples.scene_factories:make_orientation_gizmo
    config:
      size: 0.1
      margin: 0.02

controllers:
  - factory: rheidos.examples.scene_factories:make_fpv_camera_controller
    config:
      speed: 6.0
      speed_fast: 12.0
      mouse_sensitivity: 0.15
      roll_speed: 120.0
      pitch_limit_deg: 89.0
      lock_mouse: false
      invert_y: false
  - factory: rheidos.examples.scene_factories:make_screenshot_controller
    config:
      key: o
      filename: config_shot.png
  - factory: rheidos.examples.scene_factories:make_pause_controller
    config:
      key: space
  - factory: rheidos.examples.scene_factories:make_exit_controller
    config:
      key: escape

# Enable the live Scene Config panel (ImGui) for this config.
ui:
  scene_config_panel: false